name: test_flutter_vpn
description: Тестовое — экран выбора серверов (только UI)
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  device_preview: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
